package:
  name: ezc3d
  version: "0.2.0"

source:
  git_url: https://github.com/pyomeca/ezc3d

build:
  number: 4

requirements:
  host:
    - python
    - numpy

  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
    
build:
    rpath:
        - lib/
        - lib/ezc3d/
#test:
#  imports:
#    - ezc3d
    
about:
  home: https://github.com/pyomeca/ezc3d
  summary: Library to interact with c3d files

extra:
    recipe-maintainers:
        - mrtnz
