package:
  name: ezc3d
  version: "0.3.0"

source:
    git_url: https://github.com/pyomeca/ezc3d
    git_tag: Release_0.3

build:
    number: 12
    run_exports:
        strong:
            - python=3.6
            - numpy

requirements:
    host:
        - python=3.6
        - numpy
    
    build:
        - {{ compiler('cxx') }}
        - cmake
        - swig 
    
build:
    rpath:
        - lib/
        - lib/ezc3d/
#test:
#  imports:
#    - ezc3d
    
about:
  home: https://github.com/pyomeca/ezc3d
  summary: Library to interact with c3d files

extra:
    recipe-maintainers:
        - mrtnz
        - pariterre

