package:
  name: biorbd
  version: "0.1.1"

source:
  git_url: https://github.com/pyomeca/biorbd

build:
  number: 3

requirements:
  host:
    - boost
    - eigen
    - rbdl
    - dlib
    - python
    - numpy
    - swig

  build:
    - {{ compiler('cxx') }}
    - cmake

about:
  home: https://github.com/pyomeca/biorbd
  summary: .

extra:
    recipe-maintainers:
        - mrtnz
        - pariterre        
