package:
  name: dlib
  version: "19.10.0"

source:
  git_url: https://github.com/pyomeca/dlib

build:
  number: 1

requirements:
  host:
    - lapack

  build:
    # - {{ compiler('cxx') }}
    - cmake

about:
  home: https://github.com/pyomeca/dlib
  summary: Library for optimisation

extra:
    recipe-maintainers:
        - mrtnz
        - pariterre
