package:
  name: rbdl
  version: "2.5.0"

source:
  hg_url: https://bitbucket.org/rbdl/rbdl
  hg_tag: dbbbca409457

build:
  number: 0

requirements:
  host:
    - eigen

  build:
    # - {{ compiler('cxx') }}
    - cmake

about:
  home: https://bitbucket.org/rbdl/rbdl
  summary: RBDL is a highly efficient C++ library that contains some essential rigid body dynamics algorithms

extra:
    recipe-maintainers:
        - mrtnz
